### ISSUE TITLE
show absolute dates instead of relative ones

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/nodebb-theme-gruppe-adler#14]

**Comment by chris579** [comment]
outdated?

**Comment by nomisum** [comment]
cant remember what this is about

**Comment by Fusselwurm** [comment]
yes. First time I saw that NodeBB says something like "a month ago" I threw a hissy fit.

I think now it's become a bit better at not being all like "once upon a time", but it's precise on everything more than 2 days ago, so. Yeah, close.
